### ISSUE TITLE
Changes in the notifaction system at gnome

### ISSUE THREAD

**Issue by greenbigfrog** [feedindicator/Feedindicator#58]
As far as I can see this project isn't capable at all for the newer Ubuntu's.

When installing it on Ubuntu 15.04 I get following error:

``````
$ feedindicator 
Traceback (most recent call last):
  File "/usr/bin/feedindicator", line 1416, in <module>
    indicator = AppIndicator()
  File "/usr/bin/feedindicator", line 1089, in __init__
    self.update_feeds(None, True, True)
  File "/usr/bin/feedindicator", line 1355, in update_feeds
    self.send_notification(app_name, language_properties['feed_update_start_notification'], app_logo)
  File "/usr/lib/python2.7/dist-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'feed_update_start_notification'```

If I have some time left in future I might take it to look into this program!
``````

**Comment by nicolas-raoul** [comment]
Strange I am using Feedindicator on Ubuntu 2015.04 right now, and it works fine... there is probably some subtle difference in our environments.

**Comment by green-big-frog** [comment]
What phyton version are you using?

if I do `phyton --version` it tells me I'm using 2.7.9

**Comment by raelgc** [comment]
Some python packages are missing from requirements on Ubuntu, like `python-notify` and `python-gconf`. After install them, I got `feedindicator` properly working.
